-- string_in_predicate.sql
---- QUERY: string_in_predicate
-- Description : Scan fact table while applying selective in predicate filter.
-- Target test case : Basic scan and string IN filter.
SELECT count(*)
FROM lineitem
WHERE l_comment in (
  'lent asymptotes. furiously iro',
  'hely. furiously regular ideas eat. ir',
  'efully bold account',
  'the forges w',
  'the blithely final i',
  ' throughout the unusual deposits',
  'eposits nag slyly after t',
  '"e idle, pending ideas haggle even idea"',
  ' packages about the thin',
  'latelets. even ideas cajole quickly',
  'ckly carefully ruthl',
  'theodolites. c',
  'y ironically regular instructions. brave',
  'according to the slyly bold pinto beans',
  'ions. ironic ideas alongside of the i',
  'ep slyly alongside of the furiously ironi',
  '"er carefully regular, silen"',
  'hout the slyly ironi',
  '. deposits haggle furiou',
  'rnis alongside of the furious',
  'y regular plat',
  '"o beans. special, final pinto b"',
  'ven ideas poach',
  'dependencies. pending deposit',
  'slyly under the depos',
  '"ound the ironic, even dep"',
  'ly furious braids? enticing dolphins run q',
  'e regular packages. furi',
  'ges according to the carefully even package',
  'tes. specia',
  'us platelets affix furiously. carefull',
  'quests. slyly regular packa',
  ' ideas affix. carefully final deposits ar',
  'usly ironic asymptotes engage quic',
  'ously quickly fin',
  'ully even deposits',
  '"foxes. regular, careful theodoli"',
  'ites are after the f',
  '"es-- pending, ruthless instructions"',
  'alongside of th',
  's under the regular pinto bea',
  'refully even accounts ',
  ' pearls wake quick',
  ' requests.',
  'theodolites. carefully eve',
  'ly final courts',
  'theodolites? express accounts hagg',
  'y about the quickly unusual ideas. ',
  'xes. packages affi',
  's detect slyly final excuse',
  'e slyly ironic accounts. qui',
  'ously final asymptotes. quic',
  'ld pinto beans',
  'sly. slyly regular deposits against',
  'es. slyly regular packages wake blith',
  'according to th',
  'ses use slyly',
  'phs nod quickly. furiously iron',
  'l requests sleep slyl',
  'tes about the carefully fina',
  's sleep quickly: carefully',
  '"ong the even, final gr"',
  'the courts',
  'ns. blithely express instruc',
  'deposits-- furio',
  'nstructions sublate along the even ',
  'integrate fluffily behind th',
  '"iously. regular, ev"',
  'press requests are slyly slyly express p',
  '"d, final foxes. quickly ironic requests "',
  'o beans cajole blithely across',
  'ickly unusual foxes. quickly ironic sa',
  'uffily silently regular req',
  'silent deposits. speci',
  '"ironic, special theodolites. quic"',
  'ly final requests haggle slyly fluffi',
  'ent instructions. special ',
  'beans. silentl',
  '"ckages. pending, regular accou"',
  ' accounts are slyly beside the acco',
  's wake furiously.',
  '"- unusual, unusual dependencies detect s"',
  ' thrash quickly around the ',
  'sly special accounts. req',
  '"e final, final requests-- request"',
  'eat silent packages. blithely ir',
  '" with the bold, pending deposits"',
  'ns. even sheaves after the instructions sl',
  'ruthless platelets among',
  ' requests are fluffily. slyly fin',
  '"gular requests? special, ironic asym"',
  'd packages. carefully even excuses ',
  'ully ironi',
  'y express re',
  'e furiously ir',
  'thely special braids are atop t',
  'olites according to the carefu',
  'uctions engage af',
  'venly regular instructions',
  'requests x-ray slyly. carefully ',
  ' instructions. furiously even',
  'arefully even accounts use blit',
  'dazzle. ironic platelets hagg',
  'foxes boost. caref',
  'lly regular deposits slee',
  ' carefully ironic ideas.',
  'uickly regular packages sleep furiously s',
  ' use regular packages. pend',
  'refully final pinto beans. quickly speci',
  'ake blithely. quickly silent pac',
  'eep. quickly unusual platele',
  'counts. express platelets hag',
  'ogs sleep furiously after ',
  '"e carefully bold, even "',
  'yly. blithely even pin',
  ' carefully alongside of the fi',
  's cajole quickly within ',
  '" enticing, ironic packages wake slyly"',
  'to beans. fluffily unu',
  'ckly. slyly even depe',
  ' slyly bold account',
  'ic deposits haggle among ',
  'regular ideas. final accounts ',
  'riously across',
  'g. ironic ',
  'o the quickly pending ',
  'y express packages!',
  'nto beans cajole inside the alwa',
  '. slyly special dependencies wake sly',
  'y final pa',
  'round the ironic Tiresias doze ca',
  '"y above the regular, silent "',
  'y bold patterns. acc',
  '"e even, silent accounts nee"',
  'es cajole past the mu',
  'lar deposits. caref',
  'ronic instructions ',
  ' alongside of the packages. furiousl',
  'pending requests boost among th',
  ' pinto beans use furiously according to',
  'es impress against the fluffily',
  'refully unusual theod',
  'y silent platelets haggle slyly furiou',
  'y ironic instructions. bold ac',
  'ag among the packages. slyly final packages',
  '"ar, pending accounts. slyly regular pa"',
  'al deposits. quickly un',
  'fully regular accou',
  'express pinto b',
  ' courts integrate ',
  '. quickly ironic theodolites use fluff',
  ' special instruc',
  's integrate. ironic accounts i',
  'slyly ironic theodolites. carefully e',
  ' accounts. theodolites about the exc',
  'y final requests. furiously pending',
  'fluffily ironic platelets',
  'ts. slyly pending accounts are fluffily acr',
  's theodolites inside the even accounts ',
  'ithely express notornis.',
  'lithely ironic request',
  'ites haggle quickly',
  'pending pack',
  'arefully regular pinto beans dete',
  'tructions. r',
  '" engage carefully bold, even sheav"',
  'e above the iro',
  'ts use pinto beans. slyly special i',
  '"tions. final, even packages cajole quick"',
  'ily against the blithely even de',
  '" regular, "',
  'ly against ',
  ' excuses sle',
  'pinto beans. regular dolphins among ',
  'o beans use about the accoun',
  'ts. slyly final instructions sleep flu',
  'y after the carefully close asymptote',
  'n instructions. speci',
  'ily ironic deposits are after the spec',
  'ully regular requests. slyly bold th',
  'atelets sleep busil',
  '"tions boost. bold, pending pa"',
  'kages. excuses cajole',
  ' never final asym',
  'uriously silent accounts.',
  'ackages are blithely according ',
  'latelets. furiously pending pinto beans bo',
  'nusual account',
  'he carefully',
  's cajole quickly carefull',
  'ts! even packages se',
  'ges wake carefully',
  'as. quickly pending ideas',
  'p blithely. carefully express packages nag',
  'eep! slyly',
  'slyly final',
  'long the bli',
  'cajole around the flu',
  ' boost blithely pending requests.',
  's cajole s',
  'y even requests among the regular',
  'ct blithely regu',
  'mptotes. quickly final accou',
  'regular pa',
  'kages alon',
  'dazzle thinly according ',
  '"sleep about the regular packages. silent,"',
  '"ely permanent accounts use. ironic, "',
  'boost slyly into the fluffily bol',
  'ter the permanently',
  ' asymptotes cajole. blithely ir',
  'l sentiments wake furi',
  'ic requests alon',
  'regular theodolites. requests use',
  'aggle slyly ruthl',
  's along the furiously ironic ',
  'lyly expre',
  'dolites integrate carefully between the ',
  ' bold accounts',
  'ut the slyly pending deposits. furiously',
  's packages integrate quickly above the qui',
  ' dependencies',
  '"ic, special ideas poach furiously"',
  '"y regular,"',
  'lar platelets wake ',
  'latelets cajole quickly blit',
  'ent instructions affix furiously alo',
  ' carefully un',
  'ns: slyly regular requests above the',
  ' furiously above the furiously final ',
  'deas. unusual packages across the foxes sle',
  'pendencies. quick platelets haggle quickly',
  'ons. regula',
  ' even accounts brea',
  's. requests nag. ',
  'its. busily final packages i',
  'into beans are. packages ',
  's wake slyly fi',
  'ose asymptotes use blithely final pack',
  'heodolites impress care',
  'requests. theodolites ',
  'osits boost ev',
  'uffily. quick',
  'riously ironic acc',
  'ests. regular excuses br',
  '. carefully pending sauternes integrate q',
  'ent escapade',
  '"ular, special ac"',
  'lites cajole caref',
  '. slyly even reque',
  '"sual, pending packages? instructions integ"',
  'sleep carefully final ',
  'fluffily regular accounts. care',
  'g. slyly pending dependencies alongside',
  ' bold packages sleep boldly',
  ' furiously theodolites. platelets would',
  ' packages use a',
  'furious dugouts are thinly according ',
  'ffily ironic courts. fluffily ironic',
  'ly. carefully s',
  'lyly special inst',
  ' integrate fluffily regular requests. blit',
  ' are quickly. car',
  'ounts. regular foxes detect. blithe',
  'uriously instructions. carefully regular ',
  'kages about the',
  's asymptotes sleep along t',
  'carefully regular accoun',
  '"e deposits. regular, final dolphins sl"',
  'xcuses use beneath the furiously express as',
  'slyly final dolphins believe a',
  'egular depths wake quickly. blith',
  ' instructions. furiously regular gifts eat',
  'ependencies wake slyly. carefully unusual r',
  'structions. quickly ironic pack',
  '"cross the regular, special dolphins. p"',
  'ironic pinto',
  ' carefully ',
  'symptotes bo',
  'es. requests near the fluffily final fox',
  'fully regular packages: carefu',
  'he carefully even platelets need to',
  '"etect slyly ironic, bold instruction"',
  'tions wake bl',
  '" have to use fluffily regular, re"',
  '"quests across the unusual, pendi"',
  'requests haggle q',
  '. even accoun',
  'express ideas. deposits affix closely ag',
  'ithely ironic pinto bea',
  ' regular warthogs. regularly',
  ' ironic atta',
  'refully regular accounts. f',
  'tes. pinto b',
  'xes. accounts eat blithely. doggedly ironic',
  'side of the regular pinto be',
  'ns. slyly pending packages x-ray accordi',
  'ideas about the carefully regular instru',
  'ckages nag blithely carefully ',
  'p slyly. bold braids cajole enticingly',
  'refully even id',
  'alongside of the furiously pe',
  'eep furiously. blithely regular r',
  'uriously around the quickly ironi',
  ' dazzle furiously. fluffily express r',
  ' slyly. final theodolites b',
  'ructions. dolphins nag sly',
  's affix slyly across the f',
  ' regularly within the un',
  'lets. final foxes ',
  'tes cajole',
  'c requests haggle ',
  'eas sleep blithely regular',
  's against the theodolites nag against t',
  'ial theodolites whithout the final i',
  ' according to the carefully final de',
  '", even frays. fi"',
  'uickly. instruct',
  'ously even theodolites cajole accor',
  'express sauternes. regularly express ',
  '" the regular, ironi"',
  'ully deposits. specia',
  'e along the attainments. ',
  'l deposits are sly',
  ' boost carefully expres',
  'y ironic attainments cajole acco',
  'ctions. final d',
  'e furiously. quickly regular theodolites a',
  '"nder carefully. unusual, regular "',
  'y pending deposits. sly',
  'ously even accounts sl',
  ' even packages boost fluffily a',
  'deposits. quic',
  'at the slyly bold i',
  'he regular deposits? quickly regular dolph',
  'y regular pearls. slyly b',
  'nal accounts integrate qui',
  'ial accounts among the slyly regular escapa',
  'gular ideas sleep furiously. blith',
  ' deposits. blith',
  'inal dependencies. instructions mold ',
  'tealthy fo',
  '"al, even foxes. unusual packages caj"',
  'urts. final dep',
  'ove the asymptotes. e',
  ' bold platelets. quickly speci',
  'l deposits. quickly even deposits are! care',
  'gainst the furiously even foxes. packages',
  'y even foxes use.',
  'ges should use blithely unusual pinto b',
  'nic requests cajole furiously above the',
  'ss asymptotes. qui',
  'he permanently ',
  'riously regular',
  'gular requests wake. eve',
  ' ironic packages sleep blithely across the ',
  'dolphins boost. final ',
  'nusual requests',
  'ependencies ',
  'its. carefully slow excuses ha',
  'efully pending foxes. slyly ironi',
  '"xpress, regular th"',
  'l platelets i',
  '"asymptotes cajole quickly. bold, even re"',
  'ses. fluffily bold requests ',
  ' unusual instructions. de',
  '. even excuses bo',
  'sleep against the theodolites. blithe',
  'to the always regular ideas: car',
  'eas. blithely ',
  's. carefully regular dep',
  'nding platelets grow carefully. specia',
  'egular requests; carefully regular depende',
  'tions haggle according to the ironic instru',
  ' after the pint',
  'quests. carefully bold depo',
  's affix careful',
  's was blithely even escapades.',
  'onic ideas. furiously bold req',
  ' beans detect slyly b',
  'furiously regular instruc',
  'ding platelets cajo',
  'nding packages. blithely brave packa',
  'mptotes cajole slyly final instruction',
  's wake quickly fluffil',
  'ic sheaves. slyl',
  'fily ironic foxes. express packages u',
  'refully ironic accounts. final reques',
  '"ess, unusual a"',
  'thely even accounts',
  'ress instructions are carefully ac',
  's. quickly silent excu',
  ' fluffily final package',
  'ording to the asymptotes. final de',
  'ffily quickly even co',
  'counts wake against the carefully reg',
  'le along t',
  'tes alongside',
  'deposits until the quickly',
  'nal requests; ',
  'ns. blithely fin',
  'side of the blithely bold asymp',
  'le blithely. account',
  's are furiously sp',
  'aids cajole carefully fluffily bold theodol',
  'after the special notornis. fu',
  'ions snooze blit',
  'g accounts use furio',
  ' ironic the',
  'accounts affix packages. deposits de',
  'ly ironic requests. ',
  ' pending pinto beans shall wake across',
  ' across the blithely bold requests x-',
  'packages. blithely express pinto b',
  'y regular accounts hag',
  'ructions. iron',
  ' even requ',
  'kly regular requests affix fur',
  'y final accounts wa',
  'gular multipliers along the',
  'leep blithely. furiously final ',
  'lithely across the even request',
  'according to the final',
  ' the furio',
  'l deposits. regular grouches wake q',
  'cajole slyly along the carefully special ',
  '"nic foxes nag slyly. ironic, final "',
  'e slyly across the careful',
  'hely final packages sle',
  'xcuses wake blithely ir',
  ' packages wake furiously f',
  '"e carefully ironic, even p"',
  '"ously. regular, pending reque"',
  'requests! furiously regular packa',
  'ular excuses gr',
  'gular packages wake alongside',
  '". silent, "',
  'ess packages are ab',
  'furiously finally s',
  's after the bold ideas are furio',
  'ay blithely ',
  'er the fluffily quick accounts. regular ins',
  'tions. ideas are final ideas. bli',
  'e furiously. slyly',
  'jole after th',
  'old platelets. furious',
  ' theodolites. express asymptotes w',
  'ckages according to the carefully regular',
  '"lithely ironic, final re"',
  'the special instructions. even ideas hagg',
  'accounts. carefully bold packages use s',
  'regularly fina',
  'uests detect carefully furious reque',
  ' pending theod',
  'uses eat courts. blithely final ',
  'foxes. furiously final accounts are',
  ' print special deposits. close deposits a',
  '"al, even deposits. slyly pendin"',
  'thely even ideas-- regular requests cajole ',
  '", special acco"',
  'sly unusual pinto b',
  '"he bold, regular requests. furiou"',
  's dazzle blithely about the depe',
  ' silent pinto beans. instructions d',
  's the quickly fina',
  'g to the furiously',
  '"he unusual, special theodoli"',
  'fluffy deposits. bravely regular ideas ',
  ' deposits according to the slyl',
  'ep slyly at the ironic requests. pi',
  ' the final instructions. reg',
  'n accounts. final fo',
  'o beans haggle quic',
  '"l requests. express, furious pack"',
  'ckly even attainments nag',
  ' are. special packages cajole',
  'y final foxes haggle carefully. ruthless ',
  'ns cajole furiously abo',
  'sly final accounts cajole blithely ',
  'l requests was fu',
  '", express asymptotes. reg"',
  'iously silent accounts. slyly daring ',
  'onic package',
  'ilent acco',
  'y ironic depos',
  'ing theodolites. silent p',
  ' beans sublate slyly. slyly',
  'always regular c',
  'counts cajole aro',
  '"final, final packages cajole fluf"',
  'uickly along the carefully furious foxes. c',
  'structions. fluffily pending deposit',
  'among the dependen',
  'ely bold id',
  'arefully bold ',
  'ate blithely acc',
  's haggle carefully final requests. iron',
  'regular frays are',
  'tain. special packages alongsi',
  '. carefully final requests are. quickl'
)
